version: 0.0
environment_variables:
    plaintext:
        "INPUT_FILE": "saml.yaml"
       
containers:
    LambdaFunctions:
        phases:
            during_build:
                commands:
                    - npm install
                    - npm run start
                    - npm fund
                    - npm audit fix
                    
        artifacts:
            files:
                - post-saml.yaml
                - beta.json